# Sowing Success: How Machine Learning Helps Farmers Select the Best Crops

![Farmer in a field](farmer_in_a_field.jpg)

Measuring essential soil metrics such as nitrogen, phosphorous, potassium levels, and pH value is an important aspect of assessing soil condition. However, it can be an expensive and time-consuming process, which can cause farmers to prioritize which metrics to measure based on their budget constraints.

Farmers have various options when it comes to deciding which crop to plant each season. Their primary objective is to maximize the yield of their crops, taking into account different factors. One crucial factor that affects crop growth is the condition of the soil in the field, which can be assessed by measuring basic elements such as nitrogen and potassium levels. Each crop has an ideal soil condition that ensures optimal growth and maximum yield.

A farmer reached out to you as a machine learning expert for assistance in selecting the best crop for his field. They've provided you with a dataset called `soil_measures.csv`, which contains:

- `"N"`: Nitrogen content ratio in the soil
- `"P"`: Phosphorous content ratio in the soil
- `"K"`: Potassium content ratio in the soil
- `"pH"` value of the soil
- `"crop"`: categorical values that contain various crops (target variable).

Each row in this dataset represents various measures of the soil in a particular field. Based on these measurements, the crop specified in the `"crop"` column is the optimal choice for that field.  

In this project, you will build multi-class classification models to predict the type of `"crop"` and identify the single most importance feature for predictive performance.

In [316]:
# All required libraries are imported here for you.
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Load the dataset
crops = pd.read_csv("soil_measures.csv")

# Write your code here
print(crops['crop'].nunique())
print(crops.head())
print(crops['crop'].dtype)

22
    N   P   K        ph  crop
0  90  42  43  6.502985  rice
1  85  58  41  7.038096  rice
2  60  55  44  7.840207  rice
3  74  35  40  6.980401  rice
4  78  42  42  7.628473  rice
object


In [317]:
# Preprocessing the dataset
print(crops.isna().sum())
print(crops.info())

N       0
P       0
K       0
ph      0
crop    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   N       2200 non-null   int64  
 1   P       2200 non-null   int64  
 2   K       2200 non-null   int64  
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   object 
dtypes: float64(1), int64(3), object(1)
memory usage: 86.1+ KB
None


In [318]:
# creating a dummy_cat_variable
crops_dummies = pd.get_dummies(crops, drop_first = True)
print(crops_dummies.shape)
print(crops.shape)
print(crops.columns)
print(crops_dummies.columns)
dummy_cols = crops_dummies.columns[4:]
print(dummy_cols)

(2200, 25)
(2200, 5)
Index(['N', 'P', 'K', 'ph', 'crop'], dtype='object')
Index(['N', 'P', 'K', 'ph', 'crop_banana', 'crop_blackgram', 'crop_chickpea',
       'crop_coconut', 'crop_coffee', 'crop_cotton', 'crop_grapes',
       'crop_jute', 'crop_kidneybeans', 'crop_lentil', 'crop_maize',
       'crop_mango', 'crop_mothbeans', 'crop_mungbean', 'crop_muskmelon',
       'crop_orange', 'crop_papaya', 'crop_pigeonpeas', 'crop_pomegranate',
       'crop_rice', 'crop_watermelon'],
      dtype='object')
Index(['crop_banana', 'crop_blackgram', 'crop_chickpea', 'crop_coconut',
       'crop_coffee', 'crop_cotton', 'crop_grapes', 'crop_jute',
       'crop_kidneybeans', 'crop_lentil', 'crop_maize', 'crop_mango',
       'crop_mothbeans', 'crop_mungbean', 'crop_muskmelon', 'crop_orange',
       'crop_papaya', 'crop_pigeonpeas', 'crop_pomegranate', 'crop_rice',
       'crop_watermelon'],
      dtype='object')


In [319]:
# Creating the feature and target variable
X = crops.drop('crop', axis = 1).values
y = np.argmax((crops_dummies.loc[:, dummy_cols].values), axis=1)
# Checking the columns
print(X); print(y); print(y.shape)

[[ 90.          42.          43.           6.50298529]
 [ 85.          58.          41.           7.03809636]
 [ 60.          55.          44.           7.84020714]
 ...
 [118.          33.          30.           6.36260785]
 [117.          32.          34.           6.75879255]
 [104.          18.          30.           6.77983261]]
[19 19 19 ...  4  4  4]
(2200,)


In [320]:
# Spliting the data set for training and testind the model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state= 17)
print(X_train.shape); print(X_test.shape); print(y_train.shape); print(y_test.shape)

(1540, 4)
(660, 4)
(1540,)
(660,)


In [321]:
# Instanstiate the model
logreg = LogisticRegression(multi_class= 'auto')
#fit the model
logreg.fit(X_train, y_train)
# Make Predictions
y_pred = logreg.predict(X_test)
accuracy = logreg.score(X_test, y_test)
classification_report = metrics.classification_report(y_test, y_pred)
print(accuracy)
print(classification_report)

0.5803030303030303
              precision    recall  f1-score   support

           0       0.71      0.80      0.75        51
           1       0.54      0.64      0.58        33
           2       0.76      1.00      0.86        22
           3       0.35      0.45      0.39        31
           4       0.92      0.92      0.92        36
           5       0.81      0.94      0.87        31
           6       0.67      0.53      0.59        34
           7       0.49      0.81      0.61        26
           8       0.00      0.00      0.00        38
           9       0.31      0.61      0.41        23
          10       0.84      0.72      0.78        36
          11       0.54      0.43      0.48        30
          12       0.21      0.16      0.18        31
          13       0.26      0.31      0.29        29
          14       0.52      0.42      0.47        26
          15       0.87      0.79      0.83        34
          16       0.96      0.76      0.85        34
        

In [322]:
coeeficients = logreg.coef_
print(coeeficients)
features_names = list(crops.drop('crop', axis = 1).columns)
print(features_names)
features_coefficient = dict(zip(features_names, coeeficients[0]))
print(features_coefficient)
best_feature = max([abs(k) for k in features_coefficient.values()])
print(best_feature)

[[-0.13006734  0.22757181  0.75818782 -2.4332188 ]
 [-0.34467784  1.01465597 -0.86650615 -0.00451412]
 [-0.19859259 -0.02978036  0.85269408 -0.15331242]
 [-0.19970577 -0.48281422  1.05005141  0.81760984]
 [ 0.97667607 -1.24997655 -0.65463289 -0.09383291]
 [ 1.04356561 -0.42155924 -2.0724192  -0.24649075]
 [-0.21276571  0.03290754  0.84846759 -0.88060222]
 [-0.05450773 -0.01462749  0.61212744  0.11195495]
 [-0.43515287  1.08172065 -0.80299647 -0.49565247]
 [-0.46136531  1.06466656 -0.92355046  0.16999221]
 [ 0.61881933  0.15277506 -1.41297859 -0.08560569]
 [-0.22396582 -0.11561724  0.79690173  0.82925329]
 [-0.41637697  0.78731567 -0.27953705  0.4708262 ]
 [-0.41129044  0.7668812  -0.25611363  0.53173123]
 [ 0.69358233 -1.74910927  0.36771388 -0.28326267]
 [-0.0362122   0.06241693 -0.11629905  2.22167277]
 [-0.16261045  0.07203052  0.73477518 -0.29646574]
 [-0.43660133  1.07898086 -0.74971131 -0.60487165]
 [-0.24457476 -0.5085354   1.10763823  0.69368742]
 [-0.04909483 -0.01470335  0.63

In [323]:
coeeficients_df = pd.DataFrame(coeeficients, columns=features_names)
print(coeeficients_df.abs().mean().sort_values(ascending=False))
# From taking the mean of the absolute coeeficient, K seems largest wiwth an average absolute coefficient score of 0.77, We can verify this by creating individual models to see if this is correct

K     0.774738
P     0.603993
ph    0.556831
N     0.382625
dtype: float64


In [324]:
# Trying the single feature type of model 
# Creating the feature and target variable
X0 = crops['N'].values.reshape(-1,1)
y0 = np.argmax((crops_dummies.loc[:, dummy_cols].values), axis=1)
# Checking the columns
print(X0); print(y0); print(y0.shape)
# Spliting the data set for training and testind the model
X0_train, X0_test, y0_train, y0_test = train_test_split(X0, y0, test_size = 0.3, random_state= 50)
print(X0_train.shape); print(X0_test.shape); print(y0_train.shape); print(y0_test.shape)
# Instanstiate the model
logreg0 = LogisticRegression(multi_class= 'auto')
#fit the model
logreg0.fit(X0_train, y0_train)
# Make Predictions
y0_pred = logreg0.predict(X0_test)
accuracy0 = logreg0.score(X0_test, y0_test)
classification_report0 = metrics.classification_report(y0_test, y0_pred)
print(accuracy0)
print(classification_report0)

[[ 90]
 [ 85]
 [ 60]
 ...
 [118]
 [117]
 [104]]
[19 19 19 ...  4  4  4]
(2200,)
(1540, 1)
(660, 1)
(1540,)
(660,)
0.10909090909090909
              precision    recall  f1-score   support

           0       0.04      0.12      0.06        56
           1       0.07      0.31      0.12        29
           2       0.00      0.00      0.00        36
           3       0.19      0.18      0.18        34
           4       0.00      0.00      0.00        27
           5       0.42      0.82      0.55        28
           6       0.00      0.00      0.00        32
           7       0.00      0.00      0.00        42
           8       0.00      0.00      0.00        21
           9       0.14      0.32      0.19        31
          10       0.00      0.00      0.00        25
          11       0.00      0.00      0.00        27
          12       0.00      0.00      0.00        33
          13       0.00      0.00      0.00        28
          14       0.13      0.33      0.18        21
 

In [325]:
def build_model(feature, target, rv):
    X1 = feature.values.reshape(-1,1)
    y1 = np.argmax(target.values, axis=1)
    X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = 0.3, random_state= rv)
    logreg1 = LogisticRegression(multi_class= 'auto')
    logreg1.fit(X1_train, y1_train)
    y1_pred = logreg1.predict(X1_test)
    accuracy1 = logreg1.score(X1_test, y1_test)
    classification_report1 = metrics.classification_report(y1_test, y1_pred) 
    return accuracy1,classification_report1
feature = crops['P']
target = crops_dummies.loc[:, dummy_cols]
accuracy2, classification_report2 = build_model(feature, target, 312)
print(accuracy2, '\n', classification_report2)

0.17575757575757575 
               precision    recall  f1-score   support

           0       0.47      0.80      0.60        56
           1       0.00      0.00      0.00        31
           2       0.15      0.34      0.21        29
           3       0.00      0.00      0.00        35
           4       0.21      0.30      0.25        30
           5       0.00      0.00      0.00        36
           6       0.67      0.07      0.13        28
           7       0.12      0.43      0.19        28
           8       0.16      0.10      0.12        29
           9       0.00      0.00      0.00        31
          10       0.00      0.00      0.00        37
          11       0.08      0.11      0.09        27
          12       0.00      0.00      0.00        38
          13       0.00      0.00      0.00        36
          14       0.15      0.29      0.19        24
          15       0.22      0.43      0.30        30
          16       0.06      0.50      0.11        16
     

In [326]:
feature = crops['K']
target = crops_dummies.loc[:, dummy_cols]
accuracy3, classification_report3 = build_model(feature, target, 313)
print(accuracy3, '\n', classification_report3)

0.2015151515151515 
               precision    recall  f1-score   support

           0       0.24      0.31      0.27        54
           1       0.00      0.00      0.00        29
           2       0.00      0.00      0.00        33
           3       0.00      0.00      0.00        31
           4       0.00      0.00      0.00        27
           5       0.00      0.00      0.00        36
           6       0.60      0.43      0.50        35
           7       0.00      0.00      0.00        31
           8       0.00      0.00      0.00        36
           9       0.10      0.59      0.18        22
          10       0.04      0.08      0.06        25
          11       0.22      0.87      0.35        23
          12       0.14      0.07      0.09        30
          13       0.00      0.00      0.00        32
          14       0.00      0.00      0.00        36
          15       1.00      0.88      0.94        33
          16       0.00      0.00      0.00        30
      

In [327]:
feature = crops['ph']
target = crops_dummies.loc[:, dummy_cols]
accuracy4, classification_report4 = build_model(feature, target, 314)
print(accuracy4, '\n', classification_report4)

0.12575757575757576 
               precision    recall  f1-score   support

           0       0.15      1.00      0.26        57
           1       0.00      0.00      0.00        31
           2       0.14      0.52      0.22        27
           3       0.00      0.00      0.00        22
           4       0.02      0.04      0.02        24
           5       0.07      0.08      0.08        24
           6       0.00      0.00      0.00        35
           7       0.00      0.00      0.00        29
           8       0.00      0.00      0.00        36
           9       0.15      0.33      0.21        24
          10       0.00      0.00      0.00        24
          11       0.00      0.00      0.00        32
          12       0.00      0.00      0.00        37
          13       0.00      0.00      0.00        30
          14       0.00      0.00      0.00        32
          15       0.05      0.04      0.04        26
          16       0.00      0.00      0.00        27
     

In [328]:
best_predictive_feature = {'K': 0.2015151515151515}